import type { Metadata } from "next";
import { Roboto, Source_Sans_3 } from "next/font/google";
import "@/styles/globals.css";
import { Provider } from "@/components/provider";
import { Toaster } from "sonner";
import { SocketProvider } from "@/websocket";

const roboto = Source_Sans_3({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Outstagram",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Provider>
          <SocketProvider>{children}</SocketProvider>
        </Provider>
        <Toaster
          richColors
          closeButton
          position="top-right"
          toastOptions={{
            duration: 3000,
          }}
        />
      </body>
    </html>
  );
}
